#version: '3.8'

services:
  pms-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pms-backend
    restart: always
    ports:
      - "8081:8080"
    networks:
      - pms-network

  pms-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pms-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - pms-backend
    networks:
      - pms-network

networks:
  pms-network:
    driver: bridge